---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -c .github/linters/.yaml-lint.yml .
  ansible-lint ../arillso.sudoers
  flake8
platforms:
  - name: ubuntu-20.04
    image: arillso/ubuntu:20.04
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
  env:
    ANSIBLE_ROLES_PATH: ../../
verifier:
  name: ansible
